trigger:
- master
- dev
- features/*

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.0.100
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: ./build.ps1

- task: PublishBuildArtifacts@1
  displayName: 'Publish Nuget Packages to Artifacts'
  inputs:
    PathtoPublish: 'nuget'
    